added auto chooser and updated shuffleboard
FRC4048/java-common pull request #17
Opened 2024-11-22 22:55 UTC by goatfanboi23

2025-01-05 18:23 UTC, armadilloz requested changes

2025-01-05 18:23 UTC, armadilloz commented on src/main/java/org/usfirst/frc4048/common/autochooserv2/event/AutoEventProvider.java
> +        return system.getInputs().action == null ? system.getInputs().defaultAction : system.getInputs().action;
AFAICT, these are never `null` - they are set to `INVALID` in the constructor

2025-01-05 18:23 UTC, armadilloz commented on src/main/java/org/usfirst/frc4048/common/autochooserv2/event/AutoEventProvider.java
> + * Superclass of {@link AutoEventProviderIO} that uses Network Tables to get
Not really a superclass...

2025-01-06 00:28 UTC, goatfanboi23 commented on src/main/java/org/usfirst/frc4048/common/autochooserv2/event/AutoEventProvider.java
> + * Superclass of {@link AutoEventProviderIO} that uses Network Tables to get
Huh. I don't know why I wrote that...

2025-01-11 17:35 UTC, goatfanboi23 commented on src/main/java/org/usfirst/frc4048/common/autochooserv2/event/AutoEventProvider.java
> +        return system.getInputs().action == null ? system.getInputs().defaultAction : system.getInputs().action;
done

2025-01-11 17:35 UTC, noahheller commented on src/main/java/org/usfirst/frc4048/common/autochooserv2/event/AutoEventProvider.java
> + * Superclass of {@link AutoEventProviderIO} that uses Network Tables to get
done

2025-01-11 17:47 UTC, armadilloz approved these changes

2025-01-11 17:50 UTC, merged